[versions]
agp = "8.8.0"
kotlin = "2.0.0"
coreKtx = "1.15.0"
ksp = "2.0.21-1.0.27"

appcompat = "1.7.0"
material = "1.12.0"
jetbrainsKotlinJvm = "2.0.0"

navigationCompose = "2.8.6"
viewModelCompose = "2.8.7"
kotlinxCoroutines = "1.10.1"
retrofit = "2.9.0"
room = "2.6.1"
workManager = "2.9.1"
coil = "3.1.0"
hilt = "2.51.1"
hilt-navigation = "1.0.0"
timber = "5.0.1"
google-services = "4.4.2"
kakaoUser = "2.20.6"

junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.0"
coreSplashscreen = "1.0.1"
composeBom = "2025.01.01"
firebaseBom = "33.10.0"
inject = "1"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "viewModelCompose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }

kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }

androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
androidx-work-testing = { module = "androidx.work:work-testing", version.ref = "workManager" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }

converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hilt-navigation" }

javax-inject = { module = "javax.inject:javax.inject", version.ref = "inject" }

# The libraries included in the compose-bom are as follows, and the versions are most 1.7.7
#androidx.compose.animation:animation
#androidx.compose.animation:animation-core
#androidx.compose.animation:animation-graphics
#androidx.compose.foundation:foundation
#androidx.compose.foundation:foundation-layout
#androidx.compose.material:material
#androidx.compose.material:material-icons-core
#androidx.compose.material:material-icons-extended
#androidx.compose.material:material-ripple
#androidx.compose.material3:material3 - 1.3.1
#androidx.compose.material3:material3-window-size-class - 1.3.1
#androidx.compose.material3.adaptive:adaptive - 1.0.0
#androidx.compose.material3.adaptive:adaptive-layout - 1.0.0
#androidx.compose.material3.adaptive:adaptive-navigation - 1.0.0
#androidx.compose.runtime:runtime
#androidx.compose.runtime:runtime-livedata
#androidx.compose.runtime:runtime-rxjava2
#androidx.compose.runtime:runtime-rxjava3
#androidx.compose.runtime:runtime-saveable
#androidx.compose.ui:ui
#androidx.compose.ui:ui-geometry
#androidx.compose.ui:ui-graphics
#androidx.compose.ui:ui-test
#androidx.compose.ui:ui-test-junit4
#androidx.compose.ui:ui-test-manifest
#androidx.compose.ui:ui-text
#androidx.compose.ui:ui-text-google-fonts
#androidx.compose.ui:ui-tooling
#androidx.compose.ui:ui-tooling-data
#androidx.compose.ui:ui-tooling-preview
#androidx.compose.ui:ui-unit
#androidx.compose.ui:ui-util
#androidx.compose.ui:ui-viewbinding
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

# material
androidx-material = { module = "androidx.compose.material:material", name = "material" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Logging
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

# Splash
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }

# Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }

# Kakao
kakao-v2-user = { module = "com.kakao.sdk:v2-user", version.ref = "kakaoUser" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }

